#!/usr/bin/perl

#use the solid2fasta from bfast
#this generates a bash file  

open(IN, "list.of.csfasta") || die; # generated by ls *.csfasta > list.of.csfasta
while (<IN>){
	next if $_!~/csfasta$/;
	chomp();

	#change these lines to fit the naming convention
	$_=~/(L0\d)_smpl(\d+)/;
	$o="S$2_$1";

	$f=$q=$_;
	$q=~s/csfasta/QV.qual/;
	print "echo \"~/bin/solid2fastq -Z $f $q -o $o  \"\n"; 
	print "~/bin/solid2fastq -Z $f $q -o $o  \n"; 
}

